task:
  name: "Place 3 blocks among 5 targets (medium)"
  task_class_name: "GridFieldMovementTask"
  num_blocks: 6
  num_targets: 6
  allow_occupied: True
  max_occupied: 4

  grid_size: [3, 3]
  field_spacing: 0.08
  max_episode_steps: 100

colors:
  random_color: True
  max_colors: 8