# configs/tasks/place_3_line.yaml
task:
  name: "Place 2 Blocks in a Line"
  task_class_name: "BlockPlacementTask" # Specify which class handles this
  num_blocks: 2
  num_targets: 2
  num_dump_locations: 1
  allow_stacking: false
  target_layout: 'line'
  target_circle_radius: 0.15
  target_offset: [0.0, 0.0]
  spawn_bounds_relative: [-0.2, 0.2, -0.2, 0.2]
  dump_base_pos: [0.0, -0.25]
  max_episode_steps: 100