# Task: Rearrange 3 blocks into a circle pattern, dump needed
task:
  name: "Place 2 Blocks in Line"
  num_blocks: 3
  num_locations: 3
  num_dump_locations: 1
  block_scale: 0.05
  target_pattern: 'line' # Specify pattern
  # Define parameters specific to circle pattern if needed
  # circle_radius: 0.18
  # circle_center_offset: [0.15, 0.0]
rewards:
  # Can override base rewards if needed for this task
  step_penalty: -0.01
  goal_reward: 1.0
  move_fail_penalty: -0.005
# Optionally override robot parameters for this task
# robot:
#   panda:
#     gripper_closed_value: 0.020 # Maybe different for a different block size